
author = "Céline Dion"
title = "The optimal Delaunay triangulation of cheesy songs"

graduation-year = 2024
graduation-month = "November"

supervisor1 = "Prof.dr. Jan Smit"
supervisor2 = "Dr. Gerard Joling"
coreader    = "ir. Gordon Heuckeroth"

graduation-group = "3D geoinformation group"

